headersOrigin = "inline"
redirectsOrigin = "inline"

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/Users/zknexus/.openclaw/workspace/rayls-cacao/app/.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]
PRIVACY_NODE_RPC = "https://privacy-node-0.rayls.com"
DATA_CONTRACT_ADDRESS = "0x47B1C749cB7f1b48679E872E6DF3d1223cb4c6fC"
NEXT_PUBLIC_DATA_CONTRACT_ADDRESS = "0x47B1C749cB7f1b48679E872E6DF3d1223cb4c6fC"
NEXT_PUBLIC_PRIVACY_NODE_RPC = "https://privacy-node-0.rayls.com"
NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID = "d587fbee76b76abe82cee8f89db889fa"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/_next/static/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200.0
force = false

[redirects.query]
url = ":url"
w = ":width"
q = ":quality"

[redirects.conditions]

[redirects.headers]